import type { TransitionMap } from "./stateMachine";

export const ORDER_STATES = [
  "CREATED",
  "AWAITING_MODEM_PAYMENT",
  "MODEM_PAYMENT_CONFIRMED",
  "READY_FOR_PROVISIONING",
  "PROVISIONING_REQUESTED",
  "PROVISIONING_IN_PROGRESS",
  "PROVISIONING_BLOCKED",
  "READY_FOR_ACTIVATION",
  "ACTIVE",
  "SUSPENDED",
  "CANCELLATION_PENDING",
  "CANCELLED",
  "FAILED",
] as const;

export type OrderState = (typeof ORDER_STATES)[number];

export const ORDER_TRANSITIONS: TransitionMap<OrderState> = {
  CREATED: ["AWAITING_MODEM_PAYMENT", "CANCELLED"],
  AWAITING_MODEM_PAYMENT: ["MODEM_PAYMENT_CONFIRMED", "CANCELLED", "FAILED"],
  MODEM_PAYMENT_CONFIRMED: ["READY_FOR_PROVISIONING", "CANCELLATION_PENDING"],
  READY_FOR_PROVISIONING: ["PROVISIONING_REQUESTED", "CANCELLATION_PENDING"],
  PROVISIONING_REQUESTED: ["PROVISIONING_IN_PROGRESS", "PROVISIONING_BLOCKED"],
  PROVISIONING_IN_PROGRESS: [
    "READY_FOR_ACTIVATION",
    "PROVISIONING_BLOCKED",
    "FAILED",
  ],
  PROVISIONING_BLOCKED: ["PROVISIONING_IN_PROGRESS", "FAILED", "CANCELLATION_PENDING"],
  READY_FOR_ACTIVATION: ["ACTIVE", "PROVISIONING_BLOCKED"],
  ACTIVE: ["SUSPENDED", "CANCELLATION_PENDING"],
  SUSPENDED: ["ACTIVE", "CANCELLATION_PENDING"],
  CANCELLATION_PENDING: ["CANCELLED"],
  CANCELLED: [],
  FAILED: ["CANCELLED"],
};
